### ISSUE TITLE
Action does not respect the reviewdog error level

### ISSUE THREAD

**Issue by justinchuby** [jordemort/action-pyright#31]
The action produces error comments even when `level: warning` is set:

```
- name: pyright
  uses: jordemort/action-pyright@v1
  with:
    github_token: ${{ secrets.github_token }}
    reporter: github-pr-check
    level: warning
    filter_mode: diff_context
    lib: true
```

It would be great if the highest error level is reduced to the level specified in the action config.
